# Writing data to and reading data from a Database using Python (Task 4.f)

## Libraries and settings

In [4]:
# Libraries
import os
import sqlite3
import fnmatch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Function to close a sqlite db-connection
def check_conn(conn):
     try:
        conn.cursor()
        return True
     except Exception as ex:
        return False

# Get current working directory
print(os.getcwd())

/Users/john/School/Sem5/DA/data_analytics/Week_02

## Create sqlite data base

In [5]:
# Create data base
conn = sqlite3.connect('supermarkets_database.db') 
cursor = conn.cursor()

# Show dbs in the directory
flist = fnmatch.filter(os.listdir('.'), '*.db')
for i in flist:
    print(i)

supermarkets_database.db
apartment_database.db

## Create SQL-table in the database

In [11]:
cursor.execute('''CREATE TABLE IF NOT EXISTS supermarkets_table (Type VARCHAR(50),
                                                               ID INT(10),
                                                               Lat DECIMAL(5,6),
                                                               Lon DECIMAL(5,6),
                                                               Brand VARCHAR(50),
                                                               Shop VARCHAR(50),
                                                               City VARCHAR(50),
                                                               Street VARCHAR(50),
                                                               Housenumber VARCHAR(10),
                                                               Postcode VARCHAR(10))''')
# Confirm changes to the table
conn.commit()

## Read data from file to data frame

In [12]:
df = pd.read_csv('supermarkets_data_prepared.csv', 
                  sep=',', 
                  encoding='utf-8')[['type','id','lat','lon','brand','shop','city','street','housenumber','postcode']]
print(df.shape)
df.head(5)

(3392, 10)

,type,id,lat,lon,brand,shop,city,street,housenumber,postcode
0,node,33126515,47.155616,9.037915,Spar,supermarket,NaN,NaN,NaN,NaN
1,node,36726161,47.226191,8.980329,Migros,supermarket,Uznach,Zürcherstrasse,25,8730.0
2,node,39768209,47.225069,8.969981,Coop,supermarket,Uznach,NaN,NaN,8730.0
3,node,39947904,47.376732,8.542161,Coop,supermarket,Zürich,Bahnhofbrücke,1,8001.0
4,node,48932835,47.375020,8.522895,Migros,supermarket,Zürich,Wengistrasse,7,8004.0

## Write data to the SQL-table in data base

In [13]:
df.to_sql(name = 'supermarkets_table',
          con = conn,
          index = False,
          if_exists = 'replace')

3392

## Query the SQL-table

In [21]:
# Query the SQL-table
cursor.execute('''SELECT *
               FROM supermarkets_table
               WHERE City='Winterthur' ''')

df = pd.DataFrame(cursor.fetchall(), 
                  columns=['Type','Id','Lat','Lon','brand','Shop','City','Street','Housenumber','Postcode'])    
df

,Type,Id,Lat,Lon,brand,Shop,City,Street,Housenumber,Postcode
0,node,70656488,47.491874,8.706448,Migros,supermarket,Winterthur,Zürcherstrasse,102,8406.0
1,node,246533376,47.518953,8.720071,Migros,supermarket,Winterthur,Schaffhauserstrasse,152,8400.0
2,node,548919417,47.506863,8.712208,Migros,supermarket,Winterthur,Wülflingerstrasse,71,8400.0
3,node,677194765,47.503208,8.752131,None,supermarket,Winterthur,Frauenfelderstrasse,69,8404.0
4,node,706203439,47.500848,8.725938,None,supermarket,Winterthur,Bankstrasse,8/12,8400.0
5,node,709022324,47.498421,8.729118,None,supermarket,Winterthur,Steinberggasse,18,8400.0
6,node,1328945987,47.485289,8.762742,Migros,supermarket,Winterthur,Hinterdorfstrasse,40,8405.0
7,node,1519474175,47.485171,8.763196,Denner,supermarket,Winterthur,Hinterdorfstrasse,40,8405.0
8,node,3831772784,47.499163,8.721153,Migros,supermarket,Winterthur,Strickerstrasse,3,8400.0
9,node,4058248551,47.500117,8.731930,Migros,supermarket,Winterthur,Stadthausstrasse,31,8400.0
10,node,4095400178,47.501547,8.747051,None,supermarket,Winterthur,Römerstrasse,77,8404.0
11,node,4095400190,47.497901,8.724756,ALDI,supermarket,Winterthur,Archplatz,2,8400.0
12,node,4109460421,47.501010,8.722078,None,supermarket,Winterthur,Wartstrasse,14,8400.0
13,node,4125136758,47.500732,8.720169,None,supermarket,Winterthur,Neuwiesenstrasse,6,8400.0
14,node,4189897383,47.491100,8.705538,None,supermarket,Winterthur,Zürcherstrasse,120,8406.0
15,node,4209642918,47.486090,8.704346,None,supermarket,Winterthur,In der Au,10,8406.0
16,node,4379763119,47.496739,8.753231,Alnatura,supermarket,Winterthur,Industriestrasse,11,8400.0
17,node,4471606841,47.504229,8.771731,Migros,supermarket,Winterthur,Hintermühlenstrasse,4,8409.0
18,node,4816412575,47.510705,8.693819,Migros,supermarket,Winterthur,Lindenplatz,1,8408.0
19,node,4978196565,47.496801,8.746607,None,supermarket,Winterthur,Grüzefeldstrasse,24,8400.0
20,node,7418113614,47.495227,8.758614,Coop,supermarket,Winterthur,Rudolf-Diesel-Strasse,19,8404.0
21,node,7685095602,47.495833,8.749715,Migros-Outlet,supermarket,Winterthur,Industriestrasse,8,8404.0
22,node,8519878942,47.507437,8.754705,None,supermarket,Winterthur,Römerstrasse,167,8404.0
23,node,9040336565,47.477343,8.699297,Migros,supermarket,Winterthur,Ziegeleiplatz,2,8406.0
24,node,9040336566,47.477427,8.699380,Denner,supermarket,Winterthur,Ziegeleiplatz,2,8406.0
25,node,9985258254,47.510886,8.759658,ALDI,supermarket,Winterthur,Guggenbühlstrasse,6,8404.0
26,node,10221262155,47.507012,8.711808,None,supermarket,Winterthur,Wülflingerstrasse,73/75,8400.0

## Close db connection (if open)

In [22]:
# Close db connection (if open)
try:
    if check_conn(conn):
        conn.close()
    else:
        pass
except:
    pass

# Status (True = open, False = closed)
print(check_conn(conn))

False

### Jupyter notebook --footer info-- (please always provide this at the end of each submitted notebook)

In [23]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('-----------------------------------')

-----------------------------------
POSIX
Darwin | 23.0.0
Datetime: 2023-10-01 19:02:42
Python Version: 3.9.6
-----------------------------------